#./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/lecture_Building_Total_Mains_Energy.csv create insert
#./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/lecture_Floor_Total_Energy2.csv create insert 
#./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/lecture_Floor_Total_Energy0.csv create insert 
#./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/lecture_Floor_Total_Energy1.csv create insert 
#./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/lecture_AHU_Energy0.csv create insert 
#./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/AHU_Energy3.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/Lifts_Energy.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/lecture_AHU_Energy2.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/lecture_AHU_Energy1.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/AHU_Energy2.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/AHU_Energy0.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/Building_Total_Mains_Energy.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/AHU_Energy1.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/Floor_Total_Energy1.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/Floor_Total_Energy2.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/Floor_Total_Energy3.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/Floor_Total_Energy4.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/Floor_Total_Energy5.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/Light_Energy.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/UPS_Sockets_Energy.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/Building_Total_Mains_Power.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/Power_Sockets_Energy.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/Floor_Total_Power1.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/lecture_Floor_Total_Power0.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/Floor_Total_Power2.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/Lifts_Power.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/lecture_Floor_Total_Power2.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/lecture_Floor_Total_Power1.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/Floor_Total_Power5.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/Floor_Total_Power3.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/Building_Total_Mains_Current.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/Floor_Total_Power4.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/lecture_Floor_Total_Current0.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/Lifts_Current.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/Light_Power.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/lecture_Floor_Total_Current2.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/lecture_Floor_Total_Current1.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/UPS_Sockets_Power.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/UPS_Sockets_Current.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/Floor_Total_Current3.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/Floor_Total_Current1.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/Floor_Total_Current4.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/Light_Current.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/Floor_Total_Current2.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/Floor_Total_Current5.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/AHU_Power3.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/AHU_Current2.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/AHU_Power2.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/AHU_Current1.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/lecture_AHU_Power0.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/lecture_AHU_Power1.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/Power_Sockets_Power.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/Power_Sockets_Current.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/AHU_Power0.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/lecture_Building_Total_Mains_Current.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/lecture_AHU_Current0.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/lecture_AHU_Current1.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/AHU_Power1.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/lecture_Building_Total_Mains_Power.csv create insert 
#./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/AHU_Current0.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/AHU_Current3.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/lecture_AHU_Power2.csv create insert 
./netcdf /home/david/Documents/digital-twins/combed.iiitd/datasets/lecture_AHU_Current2.csv create insert 
